### PR TITLE
backport: fix: address "too many open files" error when pushing large bindles

### PR DESCRIPTION
**Pull request by endocrimes**
backporting https://github.com/deislabs/bindle/pull/337

### CODE REVIEW

**Review by technosophos — APPROVED** [review]
LGTM.

**Comment by technosophos** [comment]
I guess @radu-matei should double-check my LGTM. :-D

**Review by lann — APPROVED** [review]

**Comment by technosophos** [comment]
@lann's approval is good enough for me!

**Comment by endocrimes** [comment]
I don't think engineering gets write access to this repo rn 😅  - So I need @technosophos / @radu-matei to hit the shiny green merge button (and potentially to push a tag too)

**Review by radu-matei — APPROVED** [review]

**Pull request merged**
