### PR TITLE
Bump version to v0.8.3 and add dockerfile

### PR DESCRIPTION
**Pull request by FrankYang0529**
ref: https://github.com/fermyon/installer/pull/100#issuecomment-1309297406

### CODE REVIEW

**Comment by FrankYang0529** [comment]
Hi @vdice, I would like to add the docker release pipeline for fermyon/bindle. May you help me review it? Thank you.

**Comment by vdice** [comment]
Oh interesting approach :) I forgot we had a fork for the v0.8.0 backport(s).

As of now, the workflows for this fork are disabled:
Screenshot 2022-11-10 at 5 41 24 PM

Before enabling, we'd need to attend to a few other items in the release.yml workflow: there still are steps to publish to azure blob storage and crates.io, neither of which we're prepared to do from the fork (don't have sufficient creds, wouldn't want to overwrite).  I guess we didn't envision actually creating a release from this fork :)

I suppose one way forward would be to remove the blob storage/crates.io steps and then introduce the image push to this ghcr.io/fermyon/bindle repo.

Alternatively, if we think this may be a one-off or seldom used (i.e. eventually we'd use the images that are now being pushed in [deislabs/bindle](https://github.com/deislabs/bindle/pkgs/container/bindle) when we/downstream consumers are ready to bump to v0.9.0+), maybe instead of enabling the workflow, we manually push a `ghcr.io/fermyon/bindle/0.8.2` image based on the fermyon/0.8 branch as it stands today, for use in eg https://github.com/fermyon/installer/pull/100#issuecomment-1310430877

Let's check in with the team here - thoughts @endocrimes @dicej ?

**Comment by dicej** [comment]
Yeah, I wouldn't spend a lot of time on CI/CD for this fork, since we're planning to switch back to upstream eventually, and I doubt we'll be making many (if any) more changes here.  Manually pushing an image seems reasonable to me.

**Comment by FrankYang0529** [comment]
Yeah, if we want to switch backup to upstream eventually, manually pushing an image makes sense to me.

@vdice, may you help me create a `fermyon/bindle:v0.8.2` image for temporary use? The `Dockerfile` in this PR is different from [deislabs/bindle](https://github.com/deislabs/bindle/blob/536abea378908c9d587db69b797291f12f9eb93e/Dockerfile#L24) because we don't need `keyring.toml` in v0.8.x. After the image is pushed, feel free to close this PR. Thank you!

**Comment by vdice** [comment]
@FrankYang0529 okay, `ghcr.io/fermyon/bindle:v0.8.2` has been pushed and should be accessible.  It was built directly from the most recent commit on the `fermyon/0.8` branch.

I wouldn't oppose adding the Dockerfile and make target to this branch, but we can wait to see if we'll need to build/push from this branch in the future.

Thanks again for supplying the Dockerfile and helping with a solution here!

**Comment by FrankYang0529** [comment]
Hi @vdice, I tried to run https://github.com/fermyon/installer/pull/100 with `ghcr.io/fermyon/bindle:v0.8.2`. It looks like the architecture of the image is `arm64`. I got error `exec /usr/local/bin/bindle-server: exec format error` on nomad.

Screenshot 2022-11-14 at 9 02 18 PM

**Comment by vdice** [comment]
@FrankYang0529 Oh, sorry for the trouble here!  I've rebuilt the image for `linux/amd64` on my Apple Silicon machine via buildx and pushed that to GHCR.  Let me know if you see any further issues.

**Pull request closed without merging**
